name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2           # Package for making HTTP requests
  geolocator: ^11.1.0      
  geocoding: ^2.0.0
  shared_preferences: ^2.0.6 # Plugin for persistent storage of simple key-value pairs
  intl: ^0.19.0           # Package for internationalization and formatting
  flutter_spinkit: ^5.1.0 # Collection of loading animations
  animations: ^2.0.0      # Package for building animations and transitions
  lottie: ^3.1.2          # Package for rendering Lottie animations
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading.json
    - assets/rainy.json
    - assets/cloudy.json
    - assets/sunny.json
